sharpen: sharpen.cpp
	g++ sharpen.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./a.out sharpen.jpg

med_filter: med_filter.cpp
	g++ med_filter.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4
	./a.out car2.png
